# Minecraft
minecraft.version=1.21.1

# NeoForge
neoforge.version=21.1.93
neoforge.parchment.minecraft_version=1.21.1
neoforge.parchment.version=2024.11.17

# Forge
forge.version=52.0.39
forge.mapping_channel=parchment
forge.mapping=1.21.1-2024.11.17-1.21.1

# Fabric
fabric.loader.version=0.16.9
fabric.api.version=0.114.0+1.21.1
fabric.mapping_layer=org.parchmentmc.data:parchment-1.21.1:2024.11.17@zip

# Mod
mod.version=3.0.2
mod.snapshot=false
mod.filename=useful_backpacks
mod.name=Useful Backpacks
mod.modid=usefulbackpacks

# Publish
publish.type=stable
publish.display=Useful-Backpacks

# Curse
curse.id=274338
curse.slug=useful-backpacks

# Modrinth
modrinth.id=VLAWWg1B

# Github
github.name=Useful-Backpacks
github.branch=1.21.1

# Dependencies
jei.version=19.21.0.247
curios.version=9.2.2+1.21.1
trinkets.version=3.10.0
modmenu.fabric.version=11.0.3
